name: pagination_task
description: "A new Flutter project."
publish_to: "none"
version: 0.3.0+2

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.2
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/jsons/
